apiVersion: v1
kind: Service
metadata:
  name: first-app-service
spec:
  selector:
    app: first-app
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
